#Consider the node which deploying is having a directory /var/lib/aquiladb
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: aquiladb  
  name: aquiladb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aquiladb
  template:
    metadata:
      labels:
        app: aquiladb
    spec:
      containers:
      - image: ammaorg/aquiladb:latest
        name: aquiladb
        ports:
        - containerPort: 50051
        volumeMounts:
        - mountPath: /data
          name: aquiladb-volume
      volumes:
      - name: aquiladb-volume
        hostPath:
          path: /var/lib/aquiladb
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aquiladb
  name: aquiladb
spec:
  ports:
  - name: aquiladb-port
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: aquiladb
  type: ClusterIP
---
